import './globals.css'

export const metadata = {
  title: ' App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="min-w-min bg-white">{children}
        </main></body>
    </html>
  )
}
