import './globals.css'
import Header from './components/header'
import Footer from './components/footer'

export const metadata = {
  title: ' App',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="min-w-min bg-white">
          <Header />
          {children}
          <Footer />
        </main></body>
    </html>
  )
}
